language: java

jdk:
  - oraclejdk8

before_install:
    - java -version
    - "curl -vLJO -H 'Accept: application/octet-stream' \"https://github.com/SalesforceFoundation/ApexDoc/releases/download/1.1.7/apexdoc.jar\""
    - mkdir ~/documentation
    - ls
    - ls ~/
    - pwd

script:
    - ls
    - chmod 777 scripts/document.sh
    - ./scripts/document.sh
    - ls documentation

after_install:
    - ls documentation
