language: java

jdk:
  - oraclejdk8

env:
    global:
        secure: f/WnAh9/b8kXiEM8Uksl7kLJVqaO3Dgp9FmltGfs5MIeDEVWpENgrmDg7ov+tvmmdG8GWM5P5ip73F2eKWXk6I3OYqpCeG2B2Q89MxRa21DlK0YGnstCtBqkLysZTnpBqWtP71DtjM1cKobRPk367aFZxRRpg8BnYBLZsI5J8nhENbJ3+XfUtOYJdWb/r1RSDUNFQTQ4zk5fv87GDoUnCA/SgsErKYfud7yJSAx1mB8MzKbeGOOLJAhxtEF4iVeUlG2Dk9/kScI+aZ+foQXTl3inzJJuTEDiVvE0XxTRvZaeB7RX5qXCX8ecuiu45JIimXDijCkfvixMfkNuUtLxXASfTI95fFkHBkg11s/LGrQy7+6JTGpiJdaIgN+BS8r0+EK/3t08yfKcE6jzSpj0soz8n0Kg987GieBjLd/aDJacb9yVdL/6hLi4b+l7ovstgvnPT5uEazCBIQAzbdI7vmXIlqLFDv1bwtpT1I5S8I6JOqUNU+YyTIrwBNXfK8z8CV3TB0muBWR1e3ruVKSVSi5LswYag7h3ZPu4wAEmmpXzCzfk04k6ZOfb5lC4kTcQqywN0Uk5diXl8bfjB3OpnL3kYNjRxvwmbEG+bM2JQpgNi9B6ijI7GTfs8V30ndoR15bK156a3+ZCoTmN5gubaO9EN/v8jPECAuWBa/vJFyE=

before_install:
    - java -version
    - "curl -vLJO -H 'Accept: application/octet-stream' \"https://github.com/SalesforceFoundation/ApexDoc/releases/download/1.1.7/apexdoc.jar\""
    - mkdir ~/documentation
    - ls
    - ls ~/
    - pwd
    - ls

script:
    - ls
    - chmod 777 scripts/document.sh
    - ./scripts/document.sh
    - ls documentation/ApexDocumentation

after_success:
    [ $TRAVIS_BRANCH = master ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    sudo pip install ghp-import &&
    ghp-import -n documentation/ApexDocumentation &&
    git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
